package com.baseproject.model.entities;

public enum FeatureCode {
	SEARCH_COMPANIES, FETCH_COMPANY, CREATE_COMPANY, UPDATE_COMPANY, DELETE_COMPANY,
	SEARCH_FEATURES, FETCH_FEATURE, CREATE_FEATURE, UPDATE_FEATURE, DELETE_FEATURE,
	SEARCH_PROFILES, FETCH_PROFILE, CREATE_PROFILE, UPDATE_PROFILE, DELETE_PROFILE,
	SEARCH_USERS, FETCH_USER, CREATE_USER, UPDATE_USER, DELETE_USER, 
}
